services:
  - type: web
    name: intellects-club-website
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
